blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.BlogListView.as_view(), name='index'),
    url(
        # r'^(?P<pk>[0-9]+)-(?P<slug>[-\w]+)/$',
        r'^(?P<slug>[-_\w\d]+)/$',
        views.BlogDetailView.as_view(),
        name='detail')
]

events/urls.py
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.EventListView.as_view(), name='index'),
]

releases/urls.py
from django.conf.urls import url

from . import views

app_name = 'releases'
urlpatterns = [
    url(r'^$', views.ReleaseListView.as_view(), name='index'),
    url(
        # r'^(?P<pk>[0-9]+)-(?P<slug>[-_\w\d]+)/$',
        # r'^(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})-(?P<slug>[-_\w\d]+)/$',
        r'^(?P<slug>[-_\w\d]+)/$',
        views.ReleaseDetailView.as_view(),
        name='detail')
]

syah_site/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
# from syah import views

from core.views import HomepageView

urlpatterns = [
    url(r'^entropy/', admin.site.urls),
    # url(r'^$', views.home_page, name='home'),
    url(r'^releases/', include('releases.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^api/', include('core.api_urls', namespace='api')),
    url(r'^$', HomepageView.as_view(), name='homepage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
            ] + urlpatterns

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

from core.behaviours import PublishedManager


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    pub_datetime = models.DateTimeField(default=timezone.now)
    # mod_date = models.DateField(auto_now=True)
    slug = models.SlugField(unique=True)
    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    @property
    def is_published(self):
        return timezone.now() > self.pub_datetime

core/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models


# Create your models here.
class Venue(models.Model):
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=70)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    date = models.DateField()
    ticket_url = models.URLField(blank=True)
    info = models.TextField(blank=True, default='')

    def __str__(self):
        return '%s: %s' % (str(self.date), self.venue.name)

releases/models.py
import datetime
# import uuid

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit

from core.behaviours import PublishedManager

# Create your models here.


class Release(models.Model):
    ALBUM = 'LP'
    EP = 'EP'
    SINGLE = 'SN'
    COMPILATION = 'CM'
    LIVE = 'LV'
    RELEASE_TYPE_CHOICES = ((ALBUM, 'Album'), (EP, 'EP'), (SINGLE, 'Single'),
                            (COMPILATION, 'Compilation'), (LIVE, 'Live'), )
    release_type = models.CharField(
        max_length=2,
        choices=RELEASE_TYPE_CHOICES,
        default=ALBUM, )
    release_date = models.DateField(
        default=datetime.date.today,
        help_text="When the release is available to the public.")
    pub_datetime = models.DateTimeField(
        default=timezone.now,
        help_text="When the release will be made visible on-site.")
    title = models.CharField(max_length=500)
    slug = models.SlugField(unique=True)
    tagline = models.CharField(max_length=200, default='', blank=True)
    info = models.TextField(default='', blank=True)
    cover = models.ImageField(upload_to='covers', default='missing.gif')
    cover_thumb_300 = ImageSpecField(
        source='cover', processors=[ResizeToFit(300, 300)])
    cover_thumb_550 = ImageSpecField(
        source='cover', processors=[ResizeToFit(550, 550)])

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    @property
    def is_released(self):
        return self.release_date <= timezone.now().date()

    @property
    def is_published(self):
        return self.pub_datetime <= timezone.now()

    def get_absolute_url(self):
        return reverse('releases:detail', kwargs={'slug': self.slug})
        # return reverse(
        #     'releases:detail', kwargs={'pk': self.id,
        #                                'slug': self.slug})


class Track(models.Model):
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    length = models.DurationField()

    def __str__(self):
        return self.title


class Link(models.Model):
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    url = models.URLField()
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

blog/views.py
from django.views.generic import ListView, DetailView

from .models import Blog


# Create your views here.
class BlogListView(ListView):
    model = Blog
    ordering = '-pub_datetime'
    template_name = 'blog/index.html'

    def get_queryset(self):
        return Blog.published.all()

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['blog_active'] = True
        return context


# class BlogDetailView(CanonicalSlugDetailMixin, DetailView):
class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/detail.html'

    def get_queryset(self):
        return Blog.published.all()

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['blog_active'] = True
        return context

core/views.py
# from django.shortcuts import render
from django.views.generic import DetailView

from releases.models import Release

# Create your views here.


class HomepageView(DetailView):
    model = Release
    template_name = 'homepage.html'

    def get_object(self):
        return Release.published.filter(
            pub_datetime__isnull=False).latest('pub_datetime')

events/api/views.py
from rest_framework.generics import ListAPIView

import datetime

from ..models import Event
from .serializers import EventSerializer


class EventListAPIView(ListAPIView):
    serializer_class = EventSerializer

    def get_queryset(self):
        return Event.objects.filter(date__gte=datetime.date.today())

events/views.py
from django.views.generic import ListView

import datetime

from .models import Event


# Create your views here.
class EventListView(ListView):
    model = Event
    ordering = 'date'
    template_name = 'events/index.html'
    queryset = Event.objects.filter(date__gte=datetime.date.today())

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        context['events_active'] = True
        return context

releases/views.py
from django.views.generic import ListView, DetailView

from .models import Release


class ReleaseListView(ListView):
    model = Release
    # ordering = '-release_date'
    template_name = 'releases/index.html'

    def get_queryset(self):
        return Release.published.order_by('-release_date')

    def get_context_data(self, **kwargs):
        context = super(ReleaseListView, self).get_context_data(**kwargs)
        context['releases_active'] = True
        return context


class ReleaseDetailView(DetailView):
    model = Release
    template_name = 'releases/detail.html'

    def get_queryset(self):
        return Release.published.prefetch_related('track_set', 'link_set')

    def get_context_data(self, **kwargs):
        context = super(ReleaseDetailView, self).get_context_data(**kwargs)
        context['releases_active'] = True
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-gb">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!-- FontAwesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'syah.css' %}">
    <title>{% block title %}See You At Home{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-3">
      <div class="container">
        <a class="navbar-brand" href="{% url 'homepage' %}">See You At Home</a>
        <button type="button" class="navbar-toggler"
                data-toggle="collapse" data-target="#syah-nav-items"
                aria-controls="syah-nav-items">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="syah-nav-items">
          <ul class="navbar-nav mr-auto">
            {% block navlinks %}
            <li class="nav-item{% if releases_active %} active{% endif %}">
              <a class="nav-link" href="{% url 'releases:index' %}">Releases</a></li>
            <li class="nav-item{% if events_active %} active{% endif %}">
              <a class="nav-link" href="{% url 'events:index' %}">Events</a></li>
            <li class="nav-item{% if blog_active %} active{% endif %}">
              <a class="nav-link" href="{% url 'blog:index' %}">Blog</a></li>
            {% endblock navlinks %}
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item"><a href="https://twitter.com/seeyouuathome"><i class="nav-link fa fa-twitter fa-lg" alt="Twitter"></i></a></li>
            <li class="nav-item"><a href="https://instagram.com/seeyouuathome"><i class="nav-link fa fa-instagram fa-lg" alt="Instagram"></i></a></li>
            <li class="nav-item"><a href="https://seeyouathome.bandcamp.com/"><i class="nav-link fa fa-bandcamp fa-lg" alt="Bandcamp"></i></a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      <h1>See You At Home</h1>
      <p>Hello World! This is base.html.</p>
      {% endblock content %}
    </div>
    <!-- Javascript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | {{ blog.title }}{% endblock title %}

{% block content %}
  <h1 class="display-4 mt-3">{{ blog.title }}</h1>
  <p>{{ blog.text | linebreaks | urlizetrunc:20 }}</p>
{% endblock content %}

templates/blog/index.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | Blog{% endblock title %}

{% block content %}
  <h1 class="display-4">Blog</h1>
  <ul class="list-unstyled">
    {% for post in blog_list %}
      <li><h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> - <small class="text-muted">{{ post.pub_datetime | date:"Y-m-d"}}</small></h4></li>
    {% endfor %}
  </ul>
{% endblock content %}

templates/events/detail.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} | {{ event }}{% endblock title %}

{% block content %}
  <h1>{{ event.date }}<small> - <a href="{{ event.venue.url }}">{{ event.venue }}</a></small></h1>
  {{ event.info | linebreaks | urlizetrunc:20 }}

{% endblock content %}

templates/events/index.html
{% extends "base.html" %}

{% block title %}{{block.super }} | Events {% endblock title %}

{% block content %}
  <h1 class="display-4 mt-3">Events</h1>
  <table class="event-table table">
    <tr>
      <th>Date</th>
      <th>Venue</th>
      <th>Location</th>
      <th>Info</th>
      <th>Tickets</th>
    </tr>
    {% for event in event_list %}
      <tr>
        <td>{{ event.date }}</td>
        {% if event.venue.url %}
          <td><a href="{{ event.venue.url }}">{{ event.venue.name }}</a></td>
        {% else %}
          <td>{{ event.venue.name }}</td>
        {% endif %}
        <td>{{ event.venue.location }}</td>
        {% if event.info %}
        <td><a href="#info-toggle-{{ event.id }}" data-toggle="collapse" aria-expanded="false" aria-controls="info-toggle-{{ event.id }}">Info</a></td>
        {% else %}
          <td>-</td>
        {% endif %}
        {% if event.ticket_url %}
          <td><a href="{{ event.ticket_url }}">Tickets</a></td>
        {% else %}
          <td>Tickets not available.</td>
        {% endif %}
      </tr>
      <tr class="info-collapse collapse" id="info-toggle-{{ event.id }}">
        <!-- <div class="info collapse" id="info-toggle"> -->
          <!-- <div class="well"> -->
          <td colspan=5>
            <div class="card">
              <div class="card-header">Info</div>
              <div class="card-body">{{ event.info | linebreaks | urlizetrunc:15 }}</div>
            </div>
          </td>
          <!-- </div> -->
        <!-- </div> -->
      </tr>
    {% endfor %}
  </table>
{% endblock content %}

templates/homepage.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <a class="newest-release-cover col-md-6"
     href="{{ release.get_absolute_url }}">
    <img class="img-fluid" srcset="{{ release.cover_thumb_550.url }},
                                   {{ release.cover.url }} 2x"
                              src="{{ release.cover.url }}">
  </a>
  <div class="newest-release-info col-md-6 center-block">
    <h1>{{ release.title }}</h1>
    {% if release.is_released %}
      <p>Available now.</p>
    {% else %}
      <p>Available {{ release.release_date|date:"Y-m-d" }}.</p>
    {% endif %}

    {% if release.link_set %}
    <ul class="list-inline">
      {% for link in release.link_set.all %}
        <li class="list-inline-item">
          <a href="{{ link.url }}">{{ link.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
</div>
{% endblock content %}

templates/releases/detail.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | {{ release.title }}{% endblock title %}

{% block content %}
<h1 class="display-4 mt-3">{{ release.title }}</h1>
<!-- <img class="cover img-responsive" src="{{ release.cover.url }}" alt="cover"> -->
<div class="row">
  <div class="col-md-6">
    <a href="{{ release.cover.url }}">
      <img class="cover img-fluid"
           srcset="{{ release.cover_thumb_550.url }},
                   {{ release.cover.url }} 2x"
           src="{{ release.cover_thumb_550.url }}"
           alt="cover">
    </a>
    {% if release.tagline %}
      <p><em>{{ release.tagline }} </em></p>
    {% endif %}
  </div>
  <div class="col-md-6">
    <ol class="tracklist">
      {% for track in release.track_set.all %}
        <li>{{ track.title }} - {{ track.length }}</li>
      {% endfor %}
    </ol>
    {% if release.link_set %}
      <ul class="list-inline">
        {% for link in release.link_set.all %}
          <li class="list-inline-item"><a href="{{ link.url }}">{{ link.name }}</a></li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>
{% if release.info %}
  <p>{{ release.info | urlizetrunc:20 | linebreaks }}</p>
{% endif %}
<p>Released {{ release.release_date }}.</p>
{% endblock content %}

templates/releases/index.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Releases{% endblock title %}

{% block content %}
<h1 class="display-4 mt-3">Releases</h1>
<div class="row">
{% for rel in release_list %}
  <div class="col-6 col-md-4">
    <div class="card">
      <a href="{{ rel.get_absolute_url }}">
        <img class="card-img-top" src="{{ rel.cover_thumb_300.url }}">
      </a>
      <div class="card-body">
        <h3 class="card-title"><a href="{{ rel.get_absolute_url }}">{{ rel.title }}</a></h3>
        <!-- <h6 class="card-subtitle">{{ rel.release_date }}</h6> -->
        <p class="card-text"><small class="text-muted">{{ rel.release_date }}</small></p>
      </div>
    </div>
  </div>
{% empty %}
  <p>No releases to display.</p>
{% endfor %}
</div>
{% endblock content %}